### ISSUE TITLE
Support for multiple domains on the same app

### ISSUE THREAD

**Issue by stevenle** [grow/fileset#30]
Should be able to map multiple domains to the same fileset server, serving different manifest files.

Deployment config in grow would be something like:

```yaml
deployments:
  # deploys to example.com and all other domains
  default_domain:
    destination: fileset
    branch: auto  # Uses the git branch name.
    server: appid.appspot.com
    env:
      name: prod
      host: example.com
      scheme: https
  # deploys to foo.example.com
  subdomain_foo:
    destination: fileset
    branch: auto  # Uses the git branch name.
    server: appid.appspot.com
    domain: foo.example.com
    env:
      name: prod
      host: foo.example.com
      scheme: https
  # deploys to bar.example.com
  subdomain_bar:
    destination: fileset
    branch: auto  # Uses the git branch name.
    server: appid.appspot.com
    domain: bar.example.com
    env:
      name: prod
      host: bar.example.com
      scheme: https
```
